In [1]:
import numpy as np
import time


## SECTION 4.1 - TASK 1: UNIT CONVERSION PROGRAM

In [2]:
def convert_units():
    """
    Converts between different units of measurement.
    Supports: length, weight, volume conversions.
    """
    print("\n" + "="*60)
    print("TASK 1: UNIT CONVERSION PROGRAM")
    print("="*60)

    conversion_types = {
        '1': 'length',
        '2': 'weight',
        '3': 'volume'
    }

    length_conversions = {
        '1': ('meters to feet', lambda x: x * 3.28084),
        '2': ('feet to meters', lambda x: x / 3.28084)
    }

    weight_conversions = {
        '1': ('kilograms to pounds', lambda x: x * 2.20462),
        '2': ('pounds to kilograms', lambda x: x / 2.20462)
    }

    volume_conversions = {
        '1': ('liters to gallons', lambda x: x * 0.264172),
        '2': ('gallons to liters', lambda x: x / 0.264172)
    }

    try:
        print("\nSelect conversion type:")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")

        choice = input("Enter choice (1-3): ").strip()

        if choice not in conversion_types:
            raise ValueError("Invalid choice. Please enter 1, 2, or 3.")

        conversion_type = conversion_types[choice]

        if conversion_type == 'length':
            conversions = length_conversions
        elif conversion_type == 'weight':
            conversions = weight_conversions
        else:
            conversions = volume_conversions

        print(f"\nSelect {conversion_type} conversion:")
        for key, (desc, _) in conversions.items():
            print(f"{key}. {desc}")

        sub_choice = input("Enter choice: ").strip()

        if sub_choice not in conversions:
            raise ValueError(f"Invalid choice for {conversion_type}.")

        value = float(input("Enter value to convert: "))
        description, conversion_func = conversions[sub_choice]
        result = conversion_func(value)

        print(f"\n Result: {value} {description} = {result:.4f}")

    except ValueError as e:
        print(f"✗ Error: {e}")
    except Exception as e:
        print(f" Unexpected error: {e}")

In [3]:
convert_units()


TASK 1: UNIT CONVERSION PROGRAM

Select conversion type:
1. Length
2. Weight
3. Volume

Select length conversion:
1. meters to feet
2. feet to meters

 Result: 100.0 feet to meters = 30.4800


## SECTION 4.1 - TASK 2: MATHEMATICAL OPERATIONS ON LIST

In [4]:
def math_operations_on_list():
    """
    Performs various mathematical operations on a list of numbers.
    Operations: sum, average, maximum, minimum
    """
    print("\n" + "="*60)
    print("TASK 2: MATHEMATICAL OPERATIONS ON LIST")
    print("="*60)

    def calculate_sum(numbers):
        """Calculate sum of numbers."""
        return sum(numbers)

    def calculate_average(numbers):
        """Calculate average of numbers."""
        if len(numbers) == 0:
            raise ValueError("Cannot calculate average of empty list.")
        return sum(numbers) / len(numbers)

    def find_maximum(numbers):
        """Find maximum value in numbers."""
        if len(numbers) == 0:
            raise ValueError("Cannot find maximum of empty list.")
        return max(numbers)

    def find_minimum(numbers):
        """Find minimum value in numbers."""
        if len(numbers) == 0:
            raise ValueError("Cannot find minimum of empty list.")
        return min(numbers)

    operations = {
        '1': ('Sum', calculate_sum),
        '2': ('Average', calculate_average),
        '3': ('Maximum', find_maximum),
        '4': ('Minimum', find_minimum)
    }

    try:
        print("\nSelect operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = input("Enter choice (1-4): ").strip()

        if choice not in operations:
            raise ValueError("Invalid choice. Please enter 1-4.")

        input_str = input("Enter numbers separated by spaces: ").strip()

        if not input_str:
            raise ValueError("No numbers provided.")

        numbers = [float(x) for x in input_str.split()]

        op_name, op_func = operations[choice]
        result = op_func(numbers)

        print(f"\n {op_name}: {result}")

    except ValueError as e:
        print(f" Error: {e}")
    except Exception as e:
        print(f" Unexpected error: {e}")


In [5]:
math_operations_on_list()


TASK 2: MATHEMATICAL OPERATIONS ON LIST

Select operation:
1. Sum
2. Average
3. Maximum
4. Minimum

 Sum: 1.0


# SECTION 4.2 - LIST MANIPULATION FUNCTIONS

In [6]:
def extract_every_other(lst):
    """Extract every other element from a list, starting from the first."""
    return lst[::2]

def get_sublist(lst, start, end):
    """Return a sublist from start to end (inclusive)."""
    return lst[start:end+1]

def reverse_list(lst):
    """Reverse a list using slicing."""
    return lst[::-1]

def remove_first_last(lst):
    """Remove first and last elements from a list."""
    return lst[1:-1]

def get_first_n(lst, n):
    """Extract first n elements from a list."""
    return lst[:n]

def get_last_n(lst, n):
    """Extract last n elements from a list."""
    return lst[-n:] if n > 0 else []

def reverse_skip(lst):
    """Extract every second element starting from second-to-last, moving backward."""
    return lst[-2::-2]

# Test all list manipulation functions
print("\n" + "="*60)
print("SECTION 4.2: EXERCISE ON LIST MANIPULATION")
print("="*60)

test_list = [1, 2, 3, 4, 5, 6]

print(f"\nOriginal list: {test_list}")
print(f"1. Extract every other: {extract_every_other(test_list)}")
print(f"2. Get sublist (start=2, end=4): {get_sublist(test_list, 2, 4)}")
print(f"3. Reverse list: {reverse_list(test_list)}")
print(f"4. Remove first and last: {remove_first_last(test_list)}")
print(f"5. Get first 3 elements: {get_first_n(test_list, 3)}")
print(f"6. Get last 2 elements: {get_last_n(test_list, 2)}")
print(f"7. Reverse skip: {reverse_skip(test_list)}")


SECTION 4.2: EXERCISE ON LIST MANIPULATION

Original list: [1, 2, 3, 4, 5, 6]
1. Extract every other: [1, 3, 5]
2. Get sublist (start=2, end=4): [3, 4, 5]
3. Reverse list: [6, 5, 4, 3, 2, 1]
4. Remove first and last: [2, 3, 4, 5]
5. Get first 3 elements: [1, 2, 3]
6. Get last 2 elements: [5, 6]
7. Reverse skip: [5, 3, 1]


#SECTION 4.3 - NESTED LIST FUNCTIONS

In [7]:
def flatten(lst):
    """Flatten a nested list into a single dimension."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

def access_nested_element(lst, indices):
    """Access a specific element from a nested list given its indices."""
    current = lst
    for idx in indices:
        current = current[idx]
    return current

def sum_nested(lst):
    """Calculate sum of all elements in a nested list."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

def remove_element(lst, elem):
    """Remove all occurrences of a specific element from a nested list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

def find_max(lst):
    """Find the maximum element in a nested list."""
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

def count_occurrences(lst, elem):
    """Count occurrences of an element in a nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

def deep_flatten(lst):
    """Flatten a deeply nested list regardless of depth."""
    return flatten(lst)

def average_nested(lst):
    """Calculate average of all elements in a nested list."""
    total = sum_nested(lst)
    count = len(flatten(lst))
    return total / count if count > 0 else 0

# Test all nested list functions
print("\n" + "="*60)
print("SECTION 4.3: EXERCISE ON NESTED LISTS")
print("="*60)

nested_list = [[1, 2], [3, 4], [5]]
nested_list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
nested_list3 = [[1, 2], [3, [4, 5]], 6]
nested_list4 = [[1, 2], [2, 3], [2, 4]]
nested_list5 = [[1, 2], [3, 2], [4, 5]]
nested_list6 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
nested_list7 = [[1, 2], [3, 4], [5, 6]]

print(f"\n1. Flatten {nested_list}: {flatten(nested_list)}")
print(f"2. Access element at [1, 2] in {nested_list2}: {access_nested_element(nested_list2, [1, 2])}")
print(f"3. Sum of {nested_list3}: {sum_nested(nested_list3)}")
print(f"4. Remove 2 from {nested_list5}: {remove_element(nested_list5, 2)}")
print(f"5. Max in {nested_list3}: {find_max(nested_list3)}")
print(f"6. Count 2 in {nested_list4}: {count_occurrences(nested_list4, 2)}")
print(f"7. Deep flatten {nested_list6}: {deep_flatten(nested_list6)}")
print(f"8. Average of {nested_list7}: {average_nested(nested_list7)}")


SECTION 4.3: EXERCISE ON NESTED LISTS

1. Flatten [[1, 2], [3, 4], [5]]: [1, 2, 3, 4, 5]
2. Access element at [1, 2] in [[1, 2, 3], [4, 5, 6], [7, 8, 9]]: 6
3. Sum of [[1, 2], [3, [4, 5]], 6]: 21
4. Remove 2 from [[1, 2], [3, 2], [4, 5]]: [[1], [3], [4, 5]]
5. Max in [[1, 2], [3, [4, 5]], 6]: 6
6. Count 2 in [[1, 2], [2, 3], [2, 4]]: 3
7. Deep flatten [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]: [1, 2, 3, 4, 5, 6, 7, 8]
8. Average of [[1, 2], [3, 4], [5, 6]]: 3.5


# SECTION 10.1 - PROBLEM 1: ARRAY CREATION

In [8]:
print("\n" + "="*60)
print("SECTION 10.1 - PROBLEM 1: ARRAY CREATION")
print("="*60)

# 1. Empty array 2x2
empty_arr = np.empty((2, 2))
print(f"\n1. Empty array (2x2):\n{empty_arr}")

# 2. All ones 4x2
ones_arr = np.ones((4, 2))
print(f"\n2. Ones array (4x2):\n{ones_arr}")

# 3. Array filled with specific value
fill_arr = np.full((3, 3), 5)
print(f"\n3. Array filled with 5 (3x3):\n{fill_arr}")

# 4. Zeros like existing array
existing = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_arr = np.zeros_like(existing)
print(f"\n4. Zeros like existing array:\n{zeros_like_arr}")

# 5. Ones like existing array
ones_like_arr = np.ones_like(existing)
print(f"\n5. Ones like existing array:\n{ones_like_arr}")

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
numpy_arr = np.array(new_list)
print(f"\n6. List {new_list} converted to numpy array:\n{numpy_arr}")


SECTION 10.1 - PROBLEM 1: ARRAY CREATION

1. Empty array (2x2):
[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 1.27769376e-311]]

2. Ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 5 (3x3):
[[5 5 5]
 [5 5 5]
 [5 5 5]]

4. Zeros like existing array:
[[0 0 0]
 [0 0 0]]

5. Ones like existing array:
[[1 1 1]
 [1 1 1]]

6. List [1, 2, 3, 4] converted to numpy array:
[1 2 3 4]


# SECTION 10.1 - PROBLEM 2: ARRAY MANIPULATION

In [9]:
print("\n" + "="*60)
print("SECTION 10.1 - PROBLEM 2: ARRAY MANIPULATION")
print("="*60)

# 1. Array from 10 to 49
arr1 = np.arange(10, 50)
print(f"\n1. Array 10-49:\n{arr1}")

# 2. 3x3 matrix with values 0-8
arr2 = np.arange(9).reshape(3, 3)
print(f"\n2. 3x3 matrix (0-8):\n{arr2}")

# 3. 3x3 identity matrix
arr3 = np.eye(3)
print(f"\n3. Identity matrix (3x3):\n{arr3}")

# 4. Random array size 30, find mean
arr4 = np.random.random(30)
mean_val = arr4.mean()
print(f"\n4. Random array (size 30), mean: {mean_val:.4f}")

# 5. 10x10 random array, find min and max
arr5 = np.random.random((10, 10))
print(f"\n5. 10x10 random array - Min: {arr5.min():.4f}, Max: {arr5.max():.4f}")

# 6. Zero array size 10, replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1  # 5th element (index 4)
print(f"\n6. Zero array with 5th element = 1:\n{arr6}")

# 7. Reverse array
arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr7[::-1]
print(f"\n7. Reverse {arr7}:\n{reversed_arr}")

# 8. 2D array with 1 on border, 0 inside
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print(f"\n8. 2D array with border 1s, inside 0s:\n{arr8}")

# 9. 8x8 checkerboard pattern
arr9 = np.zeros((8, 8))
arr9[::2, ::2] = 1
arr9[1::2, 1::2] = 1
print(f"\n9. 8x8 checkerboard pattern:\n{arr9}")


SECTION 10.1 - PROBLEM 2: ARRAY MANIPULATION

1. Array 10-49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0-8):
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array (size 30), mean: 0.5001

5. 10x10 random array - Min: 0.0155, Max: 0.9817

6. Zero array with 5th element = 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reverse [1 2 0 0 4 0]:
[0 4 0 0 2 1]

8. 2D array with border 1s, inside 0s:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 checkerboard pattern:
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# SECTION 10.1 - PROBLEM 3: ARRAY OPERATIONS

In [10]:
print("\n" + "="*60)
print("SECTION 10.1 - PROBLEM 3: ARRAY OPERATIONS")
print("="*60)

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print(f"\nx = \n{x}")
print(f"\ny = \n{y}")
print(f"\nv = {v}")
print(f"w = {w}")

# 1. Add arrays
print(f"\n1. x + y =\n{x + y}")

# 2. Subtract arrays
print(f"\n2. x - y =\n{x - y}")

# 3. Multiply by integer
print(f"\n3. x * 2 =\n{x * 2}")

# 4. Square of each element
print(f"\n4. x^2 =\n{x ** 2}")

# 5. Dot products
print(f"\n5. Dot products:")
print(f"   v · w = {np.dot(v, w)}")
print(f"   x · v = {np.dot(x, v)}")
print(f"   x · y = {np.dot(x, y)}")

# 6. Concatenate
print(f"\n6. Concatenation:")
print(f"   x and y along rows:\n{np.vstack((x, y))}")
print(f"   v and w along columns:\n{np.column_stack((v, w))}")

# 7. Concatenate x and v (will show error)
print(f"\n7. Concatenate x and v:")
try:
    result = np.concatenate((x, v))
    print(f"   Result: {result}")
except ValueError as e:
    print(f"   Error: {e}")
    print(f"   Reason: x has shape {x.shape} (2D) and v has shape {v.shape} (1D).")
    print(f"   They cannot be concatenated directly without reshaping.")


SECTION 10.1 - PROBLEM 3: ARRAY OPERATIONS

x = 
[[1 2]
 [3 5]]

y = 
[[5 6]
 [7 8]]

v = [ 9 10]
w = [11 12]

1. x + y =
[[ 6  8]
 [10 13]]

2. x - y =
[[-4 -4]
 [-4 -3]]

3. x * 2 =
[[ 2  4]
 [ 6 10]]

4. x^2 =
[[ 1  4]
 [ 9 25]]

5. Dot products:
   v · w = 219
   x · v = [29 77]
   x · y = [[19 22]
 [50 58]]

6. Concatenation:
   x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
   v and w along columns:
[[ 9 11]
 [10 12]]

7. Concatenate x and v:
   Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
   Reason: x has shape (2, 2) (2D) and v has shape (2,) (1D).
   They cannot be concatenated directly without reshaping.


***

## Problem 4: Matrix Operations

In [11]:
A =np.array([[3,4],[7,8]])
B =np.array([[5,3],[2,1]])
print("matrix A:\n", A)
print("matrix B:\n", B)


matrix A:
 [[3 4]
 [7 8]]
matrix B:
 [[5 3]
 [2 1]]


In [12]:
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)

print("\nA inverse:\n", A_inv)
print("\nA * A_inv:\n", identity_check)


A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [13]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nA * B:\n", AB)
print("\nB * A:\n", BA)

print("\nIs AB equal to BA?")
print(np.allclose(AB, BA))


A * B:
 [[23 13]
 [51 29]]

B * A:
 [[36 44]
 [13 16]]

Is AB equal to BA?
False


In [14]:
AB_transpose = (AB).T
BT_AT = np.dot(B.T, A.T)

print("\n(AB)^T:\n", AB_transpose)
print("\nB^T * A^T:\n", BT_AT)

print("\nIs (AB)^T equal to B^T A^T?")
print(np.allclose(AB_transpose, BT_AT))


(AB)^T:
 [[23 51]
 [13 29]]

B^T * A^T:
 [[23 51]
 [13 29]]

Is (AB)^T equal to B^T A^T?
True


# Solve System of Linear Equations
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# Represent AX = B

In [15]:
A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]])

B_sys = np.array([[-1],
                  [-3],
                  [9]])

print("\nMatrix A (system):\n", A_sys)
print("\nMatrix B (system):\n", B_sys)


Matrix A (system):
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Matrix B (system):
 [[-1]
 [-3]
 [ 9]]


# Solve using Inverse Method

In [16]:
A_sys_inv = np.linalg.inv(A_sys)

X = np.dot(A_sys_inv, B_sys)

print("\nSolution using Inverse Method:")
print("x =", X[0][0])
print("y =", X[1][0])
print("z =", X[2][0])


Solution using Inverse Method:
x = 2.0
y = 1.0
z = -2.0


# Solve directly using np.linalg.inv

In [17]:
X_direct = np.linalg.inv(A_sys).dot(B_sys)

print("\nSolution using np.linalg.inv directly:")
print(X_direct)



Solution using np.linalg.inv directly:
[[ 2.]
 [ 1.]
 [-2.]]
